### PR TITLE
Add precompilation step for cra apps

### PR DESCRIPTION
**Pull request by Shahor**

### CODE REVIEW

**Comment by Maher4Ever** [comment]
Would to see this merged and released as soon as possible!

**Comment by jhnns** [comment]
Awesome 👍. Shipped with [`v2.1.2`](https://github.com/peerigon/parse-domain/releases/tag/v2.1.2)

**Comment by Maher4Ever** [comment]
Unfortunately, issue #26 still happens with `v2.1.2` 😞

**Comment by jhnns** [comment]
That's probably because *there is no precompilation* step 😁. I asked if [cra picks up the `.babelrc`](https://github.com/peerigon/parse-domain/pull/27#issuecomment-396348295) but received no answer. Since I'm not using cra and I don't know about the internals, I assumed that this change would fix it.

**Comment by Maher4Ever** [comment]
@jhnns [CRA expects used modules to be pre-compiled](https://github.com/facebook/create-react-app/blob/master/packages/react-scripts/template/README.md#npm-run-build-fails-to-minify). Adding a pre-compilation step before publishing `parse-domain` wouldn't be that difficult right?

**Pull request merged**
