### PR TITLE
Fix dependencies

### LINKED ISSUE #34: ⚠️ dev-dependencies were added as dependencies in 2.1.1
[In 2.1.1 package.json](https://github.com/peerigon/parse-domain/blob/v2.1.1/package.json#L30) 
```
  "dependencies": {
    "chai": "^4.1.2",
    "fs-copy-file-sync": "^1.1.1",
    "got": "^8.0.1",
    "mkdirp": "^0.5.1",
    "mocha": "^4.0.1"
  },
  "devDependencies": {
    "eslint": "^4.12.1",
    "eslint-config-peerigon": "^12.0.1",
    "eslint-plugin-import": "^2.8.0",
    "eslint-plugin-jsdoc": "^3.2.0",
    "nyc": "^11.3.0",
    "standard-version": "^4.2.0"
  }
```

I noticed it because I have a max size limit for dependencies 😉

### PR DESCRIPTION
**Pull request by Jolg42**
Fixes #34 

Because some "dev-dependencies" were in "dependencies"

### CODE REVIEW

**Comment by Jolg42** [comment]
By the way dev-dependencies could be updated
screenshot 2018-06-01 at 16 54 52
(I didn't update them in this PR)

**Comment by jhnns** [comment]
Thanks for pointing it out 😁. However, this change was actually intended.

The [Public Suffix List](https://publicsuffix.org/learn/) asks developer not to "bake" the list into the software:

> Some people use the PSL to determine what is a valid domain name and what isn't. This is dangerous, particularly in these days where new gTLDs are arriving at a rapid pace, if your software does not regularly receive PSL updates, because it will erroneously think new gTLDs are not valid. The DNS is the proper source for this information. If you must use it for this purpose, please do not bake static copies of the PSL into your software with no update mechanism. 

I decided to download the list on `postinstall` for this reason (see README). Hence, you'll receive an updated list for every deploy. In order to verify the integrity of the list, we also run the tests during `postinstall`. If something goes wrong, we fall back to a pre-compiled list that has been created when the module was published on NPM.

Hope that clarifies it. Do you have a different idea how we could fix that? If yes, please re-open 😁

**Comment by Jolg42** [comment]
Got it, thanks for the explanation! 👍  I guess I'll use my fork or try tld.js

By the way it's interesting that for tld.js they offer to save a npm boolean for updating the list like `npm install --tldjs-update-rules`

**Comment by jhnns** [comment]
Could you elaborate on your particular problem? What dependency limit do you have?

**Comment by Jolg42** [comment]
It's 1MB for all the code / dependencies for AWS Lambda@Edge ([see official doc](https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/cloudfront-limits.html#limits-lambda-at-edge))

**Comment by jhnns** [comment]
Wow 1MB is really small. I wonder how many node modules are below this limit 😁.

The runtime size of parse-domain should be really small because all dependencies from the `package.json` are only used during build time. Do you have an idea how we could separate them so that use could use the library?

**Comment by wopian** [comment]
Install size has ballooned from 418 KB to 3.71 MB with `~2.1.0` https://packagephobia.now.sh/result?p=parse-domain@2.1.0

**Pull request closed without merging**
