### PR TITLE
chore(core): update deps and fix a potential vuln

### PR DESCRIPTION
**Pull request by acidicX**
should fix https://github.com/dominictarr/event-stream/issues/116

Note: to upgrade to got 9 we would need to drop node 6 and 7 support.
But this package could be used on node 6 & 7, it just won't build on the platform.

### CODE REVIEW

**Comment by jhnns** [comment]
👍

`got` is not critical now, so it's good to keep the old version, so we can push a non-breaking change.

**Comment by jhnns** [comment]
Published as `2.1.7` 🚀

**Review by IzmaDoezIt — CHANGES_REQUESTED** [review]
Great work.

**Comment by PannawatC** [comment]
Go

**Comment by indragunawan98** [comment]
#200

**Pull request merged**
