### PR TITLE
handle line breaks special characters in url string

### LINKED ISSUE #20: unable to parse domain with specialcharacters in the end
sometimes we're getting such referer `http://m.facebook.com\r`. and in this case parse-domain is unable to parse domain correctly

### PR DESCRIPTION
**Pull request by skarbovskiy**
Close #20

### CODE REVIEW

**Comment by skarbovskiy** [comment]
@alsotang @jhnns @mattlubner @akost is this repo alive?

**Comment by mattlubner** [comment]
I'm not sure, as I haven't used `parse-domain` in quite some time. Kinda surprising to see that I was such a major contributor, though!

**Comment by alsotang** [comment]
@skarbovskiy use this package https://github.com/oncletom/tld.js

**Comment by alsotang** [comment]
`tld.js` also has benchmark. The speed of `parse-domain` is slow

**Comment by jhnns** [comment]
Thanks @skarbovskiy 👍. Shipped as `1.2.0`
@alsotang can you give me some numbers how `parse-domain` is slower?

**Comment by alsotang** [comment]
@jhnns oh, it's my fault. The benchmark speed of `tld.js` and `parse-domain` is almost the same.

Once I write a cpu-intensive program. I write a benchmark for `parse-domain` , about 10k~20k ops per second.

**Comment by jhnns** [comment]
> The benchmark speed of tld.js and parse-domain is almost the same.

That's interesting. Because `parse-domain` uses a big regex and `tld.js` is trie-based afaik. I'd expect trie-based to be faster but would be interested in actual numbers.

[I'm currently working on switching to a trie-based solution](https://github.com/peerigon/parse-domain/tree/refactor/improve-file-size) because it also makes the code smaller (which is important in cases where the module is used in the browser). I'm also planning to add a fast path for common tlds like `.com` and `.org`.

**Pull request merged**
