### PR TITLE
fix: move Jest to dev dependencies, close #89

### LINKED ISSUE #89: Remove `jest` from dependencies
Is a testing framework really needed as a dependency or should it maybe have been in `devDependencies`? Noticed it because of these deprecations:

```
parse-domain > jest > jest-cli > @jest/core > jest-haste-map > fsevents@1.2.9: One of your dependencies needs to upgrade to fsevents v2: 1) Proper nodejs v10+ support 2) No more fetching binaries from AWS, smaller package size
parse-domain > jest > jest-cli > jest-config > jest-environment-jsdom > jsdom > left-pad@1.3.0: use String.prototype.padStart()

### PR DESCRIPTION
**Pull request by bahmutov**
- closes #89 

Note: this throws this error, which does not affect the install
```
Running sanity check... 
Could not update list of known top-level domains for parse-domain because of "Cannot find module '.bin/jest'
Require stack:
- /private/tmp/node_modules/parse-domain/scripts/build-tries.js"
```

### CODE REVIEW

**Comment by flotwig** [comment]
@bahmutov won't this make the step to build the fresh public suffix list always fail? I have no earthly clue *why* it requires `jest`, but it does, or it will throw here and won't complete:

https://github.com/peerigon/parse-domain/blob/9246927990982c4854e490785855c33d3217ac07/scripts/build-tries.js#L77-L80

**Comment by flotwig** [comment]
The line above it says "Running sanity check", so I'm guessing the purpose is to run all the Jest specs using the new data before committing it. I guess that makes sense to do but.... it also seems likely that the relevant specs could be extracted, re-written to use basic assertions, and then it wouldn't need the prod dependency on `jest`.

**Comment by bahmutov** [comment]
yes, it does include Jest just to run a basic test, which is not good in production mode

**Comment by flotwig** [comment]
Not to mention the jest test seems to fail: https://github.com/peerigon/parse-domain/issues/90

**Comment by jhnns** [comment]
Yes, Jest is a regular dependency. Jest is not used at runtime but on every `npm install`. However, some people had problems with this approach (https://github.com/peerigon/parse-domain/issues/42) so we will revert it back to manual updates.

**Comment by schmod** [comment]
@jhnns Anything we can do to help?

**Comment by jhnns** [comment]
Nope, thanks. It's almost finished :)

**Pull request closed without merging**
