### PR TITLE
add icann option

### PR DESCRIPTION
**Pull request by alsotang**
fix issue #4  #6

### CODE REVIEW

**Comment by alsotang** [comment]
ping @jhnns

**Comment by jhnns** [comment]
Awesome, thx! 👍 I was just about to write that for myself :)

I've merged this PR locally because it had a conflict. I'll publish a 1.0.0 tomorrow.

FYI: I've renamed `options.icann` to `options.includePrivateTlds` which is `false` by default. I think, most users would not expect `blogspot.com` to be a TLD.

**Comment by alsotang** [comment]
Yeah, I also think most user dont want to non-icann tlds. That socall effective-private-tld always make misunderstand.

**Comment by alsotang** [comment]
can we just name the option `private`?

**Comment by jhnns** [comment]
We can name it `privateTlds`, but `private` is too generic

**Comment by alsotang** [comment]
ok, I agree with we should use a non-generic name.

And should we make `privateTlds : false` a default option?

I think the feature of private tld is unpredictable and obscure. I really doubt that how many people would rely on this feature.

If we still make `privateTlds: true` default, does the harm of the confusion of new users greater than its compatibility?

**Comment by jhnns** [comment]
Yes, it should be `privateTlds: false` by default. I tripped over it too.

**Pull request closed without merging**
