### PR TITLE
Return null if urlSplit is null - fix issues 32 and 61

### PR DESCRIPTION
**Pull request by dydeepak97**

### CODE REVIEW

**Comment by jhnns** [comment]
Thank you for your PR and for adding tests ❤️. This has already been addressed with https://github.com/peerigon/parse-domain/pull/63

**Comment by dydeepak97** [comment]
The changes in #63 will not cover the case of these character being present with other valid charcter. e.g., https://www.hell\no.com. \n charater present in url will cause the same error.

**Comment by jhnns** [comment]
You're right, sorry. It was too late yesterday :)

**Comment by dydeepak97** [comment]
Can you make a new release with this change included ?

**Comment by jhnns** [comment]
Published with `v2.2.1` 🚀

**Pull request merged**
